### ISSUE TITLE
Mod Prevents Skeletons dropping Bone Fragments

### ISSUE THREAD

**Issue by JMCY26** [werner-mayer/valheimerasystem#1]
Hi,

The discord link is dead on the mod page so I couldn't join the discord.

This mod, prevents skeletons from dropping bone fragments and I cannot see anything regarding it in the configuration settings?

Unless I'm missing something, this is unintended? 

Regards

**Edit: Ignore me, I see undead are restricted to Iron, I assumed it would have been available for Bronze as they are both in the Black Forest.**

**Comment by werner-mayer** [comment]
just FYI the initial config is just a sketch, you probably would like to change it to whatever you want
